server.port=8081

#--------------- CONEXIÓN A BD ---------------
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Splitsee
spring.datasource.username=postgres
spring.datasource.password=1234678

# Inicialización SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Generar/actualizar esquema desde entidades (solo DEV)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logs de SQL (dev)
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
